{
  "name": "davy",
  "version": "0.3.0",
  "author": {
    "name": "Yehor Lvivski",
    "email": "lvivski@gmail.com"
  },
  "description": "Promises/A+ implementation",
  "keywords": [
    "promise",
    "a+",
    "then",
    "async"
  ],
  "dependencies": {
    "subsequent": "*"
  },
  "scripts": {
    "test": "promises-aplus-tests test/adapter",
    "prepublish": "make -B"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/lvivski/davy.git"
  },
  "devDependencies": {
    "uglify-js": "*",
    "promises-aplus-tests": "*"
  },
  "license": "MIT",
  "readme": "<a href=\"http://promisesaplus.com/\">\n    <img src=\"http://promisesaplus.com/assets/logo-small.png\" alt=\"Promises/A+ logo\"\n         title=\"Promises/A+ 1.0 compliant\" align=\"right\" />\n</a>\n\n# Davy Jones\n\nYet another [Promises/A+](http://promises-aplus.github.com/promises-spec) implementation optimized for speed and simplicity.\n\n## API\n\n####`new Davy(resolver)`\nCreate a new promise. The passed in function will receive functions resolve and reject as its arguments which can be called to seal the fate of the created promise.\n\n####`.then(onFulfill, onReject)`\nReturns a new promise chained from this promise. The new promise will be rejected or resolved defer on the passed `onFulfill`, `onReject` and the state of this promise.\n\n####`.catch(handler)`\nThis is a catch-all exception handler, shortcut for calling `.then(null, handler)` on this promise. Any exception happening in a `.then`-chain will propagate to nearest `.catch` handler.\n\n###`.throw(handler)`\nLike `.catch`, but any unhandled rejection that ends up here will be thrown as an error.\n\n###`.finally(handler)`\nPass a handler that will be called regardless of this promise's fate. Returns a new promise chained from this promise.\n\n####`.spread(onFulfill, onReject)`\nLike calling .then, but the fulfillment value or rejection reason is assumed to be an array, which is flattened to the formal parameters of the handlers.\n\n####`Davy.resolve(value)`\nReturns a Promise object that is resolved with the given value. If the value is a thenable (i.e. has a then method), the returned promise will \"follow\" that thenable, adopting its eventual state; otherwise the returned promise will be fulfilled with the value.\n\n####`Davy.reject(reason)`\nReturns a Promise object that is rejected with the given reason.\n\n####`Davy.defer()`\nCreate a promise with undecided fate and return a Resolver to control it.\n\n####`Davy.all(iterable)`\nReturns a promise that resolves when all of the promises in `iterable` have resolved. The result is passed an array of values from all the promises. If something passed in the `iterable` array is not a promise, it's converted to one by Promise.cast. If any of the passed in promises rejects, the all Promise immediately rejects with the value of the promise that rejected, discarding all the other promises whether or not they have resolved.\n\n####`Davy.race(iterable)`\nReturns a promise that either resolves when the first promise in the `iterable` resolves, or rejects when the first promise in the `iterable` rejects.\n\n####`Davy.wrap(nodeFunction)`\nReturns a function that will wrap the given `nodeFunction`. Instead of taking a callback, the returned function will return a promise whose fate is decided by the callback behavior of the given node function. The node function should conform to node.js convention of accepting a callback as last argument and calling that callback with error as the first argument and success value on the second argument.\n",
  "readmeFilename": "README.md",
  "bugs": {
    "url": "https://github.com/lvivski/davy/issues"
  },
  "homepage": "https://github.com/lvivski/davy",
  "_id": "davy@0.3.0",
  "dist": {
    "shasum": "e20eb2c2aae167c18efe2bd43fa23846cde88d06"
  },
  "_from": "davy@0.3.0",
  "_resolved": "https://registry.npmjs.org/davy/-/davy-0.3.0.tgz"
}
